### ISSUE TITLE
property name? camelcase

### ISSUE THREAD

**Issue by hyundae** [xebia/jackson-lombok#3] opened 2015-07-23 02:36 UTC
can not english.
only source code + result 

import java.util.List;

import lombok.Data;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

public class LombokJacksonTest {

```
public static void main(String[] args) throws Exception {
    String json = "[{\"cName\":\"b\"}]";
    ObjectMapper om = new ObjectMapper();

    List<Model1> list1 = om.readValue(json, new TypeReference<List<Model1>>(){});
    List<Model2> list2 = om.readValue(json, new TypeReference<List<Model2>>(){});
    System.out.println( om.writer().writeValueAsString(list1) );        //[{"cname":null}]
    System.out.println( om.writer().writeValueAsString(list2) );        //[{"cName":"b"}]
}
```

}
@Data
@JsonIgnoreProperties(ignoreUnknown = true)
class Model1 {
    private String cName;
}

@JsonIgnoreProperties(ignoreUnknown = true)
class Model2{
    private String cName;
    public String getcName() {
        return cName;
    }
    public void setcName(String cName) {
        this.cName = cName;
    }
}

--difference two case
[{"cname":null}]                 --X
[{"cName":"b"}]                 --O

--jsonarray test
JSONArray jarray = JSONArray.fromObject(json);

```
    for(int i=0; i<jarray.size(); i++) {
        JSONObject jobj = jarray.getJSONObject(i);
        System.out.println(jobj.toString());
    }
```

{"cName":"b"}

**Comment by kazuki-ma** [comment] 2015-07-24 17:43
It's jackson's spec or problem.
Those works fine.

``` java
@Data
@JsonIgnoreProperties(ignoreUnknown = true)
class Model1 {
  @JsonProperty("cName")
  String cname; // not cName;
}
```

OR 

``` java
@Data
@JsonIgnoreProperties(ignoreUnknown = true)
class Model2 {
  @Getter(onMethod = @__(@JsonProperty("cName")))
  @Setter(onMethod = @__(@JsonProperty("cName")))
  String cName;
}
```

**Comment by kazuki-ma** [comment] 2015-07-24 17:52
Sorry I'm something wrong.

the name of accessor method of the field `cName` should `setcName`?
Lombok create `setCName` but eclipse create `setcName`.

**Comment by 0xR** [comment] 2015-07-28 11:43
Can you provide a unit test which demonstrates the issue? I'm not sure that I understand.

**Comment by 0xR** [comment] 2016-01-30 12:24
I am closing this issue as it is unclear what the problem is.

**Closed as completed by 0xR** 2016-01-30 12:24 UTC

**Comment by Danceiny** [comment] 2018-10-23 08:05
@0xR refer to: https://stackoverflow.com/questions/30205006/why-does-jackson-2-not-recognize-the-first-capital-letter-if-the-leading-camel-c
